// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

/************************************************************/
/**
 * 
 */
public class Classe  {
	/**
	 * 
	 */
	//test commit
	
	
	
	private String id;
	/**
	 * 
	 */
	private int promotion;
	/**
	 * 
	 */
	private String filiere;
	/**
	 * 
	 */
	public Personne[] personne;

	/**
	 * 
	 * @param id 
	 * @param promotion 
	 * @param filiere 
	 */
	public Classe(String id, int promotion, String filiere) {
		this.id = id;
		this.promotion = promotion;
		this.filiere = filiere;
	}
};
