// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Creneau extends SqlUtils {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private LocalTime debut;
	/**
	 * 
	 */
	private LocalTime fin;
	/**
	 * 
	 */
	private LocalDate jour;
	/**
	 * 
	 */
	public Classe classe;
	public UniteEnseignement uniteEnseignement;

	/**
	 * 
	 * @param id
	 * @param debut
	 * @param fin
	 * @param jour
	 */
	public Creneau(String id, LocalTime debut, LocalTime fin, LocalDate jour) {
		this.id = id;
		this.debut = debut;
		this.fin = fin;
		this.jour = jour;
	}

	public void save() {
		this.connect();
		this.requestUpdate(String.format("INSERT INTO CRENEAU VALUES('%s','%s','%s','%s','%s','%s')", this.id,
				this.debut.toString(), this.fin.toString(), this.jour.toString(),
				this.classe == null ? "" : this.classe.getId(),
				this.uniteEnseignement == null ? "" : this.uniteEnseignement.getId()));
		this.disconnect();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public LocalTime getDebut() {
		return debut;
	}

	public void setDebut(LocalTime debut) {
		this.debut = debut;
	}

	public LocalTime getFin() {
		return fin;
	}

	public void setFin(LocalTime fin) {
		this.fin = fin;
	}

	public LocalDate getJour() {
		return jour;
	}

	public void setJour(LocalDate jour) {
		this.jour = jour;
	}

	public Classe getClasse() {
		return classe;
	}

	public void setClasse(Classe classe) {
		this.classe = classe;
	}

	public UniteEnseignement getUniteEnseignement() {
		return uniteEnseignement;
	}

	public void setUniteEnseignement(UniteEnseignement uniteEnseignement) {
		this.uniteEnseignement = uniteEnseignement;
	}

	public void update() {
		this.connect();
		this.requestUpdate(String.format(
				"UPDATE CRENEAU SET debut='%s',fin='%s',jour='%s',classe='%s',uniteEnseignement='%s' WHERE id='%s'",
				this.id, this.debut.toString(), this.fin.toString(), this.jour.toString(),
				this.classe == null ? "" : this.classe.getId(),
				this.uniteEnseignement == null ? "" : this.uniteEnseignement.getId(), this.id));
		this.disconnect();
	}

	public void delete() {
		this.connect();
		this.requestUpdate(String.format("DELETE FROM CRENEAU WHERE id='%s'", this.id));
		this.disconnect();

	}

	public static Creneau getById(String id) {
		SqlUtils sql = new SqlUtils();
		sql.connect();
		ResultSet set = sql.requestSelect(String.format("SELECT * FROM CRENEAU WHERE id='%s'", id));

		try {
			Creneau creneau = new Creneau(set.getString("id"), LocalTime.parse(set.getString("debut")),
					LocalTime.parse(set.getString("fin")), LocalDate.parse(set.getString("jour")));
			sql.disconnect();
			return creneau;
		} catch (SQLException e) {
			e.printStackTrace();
			sql.disconnect();
			return null;
		}
	}

	public static List<Creneau> getAll() {
		SqlUtils sql = new SqlUtils();
		sql.connect();
		ResultSet set = sql.requestSelect(String.format("SELECT * FROM CRENEAU"));
		
		List<Creneau> result = new ArrayList<Creneau>();

		try {
			while (set.next()) {
				Creneau creneau = new Creneau(set.getString("id"), LocalTime.parse(set.getString("debut")),
						LocalTime.parse(set.getString("fin")), LocalDate.parse(set.getString("jour")));
				result.add(creneau);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			sql.disconnect();
			return null;
		}
		sql.disconnect();
		return result;
	}

	@Override
	public String toString() {
		return "" + id + " ; " + debut + " ; " + fin + " ; " + jour + "\n";
	}
	
};
