// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

import java.time.LocalDate;
import java.time.LocalTime;

/************************************************************/
/**
 * 
 */
public class Creneau {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private LocalTime debut;
	/**
	 * 
	 */
	private LocalTime fin;
	/**
	 * 
	 */
	private LocalDate jour;
	/**
	 * 
	 */
	public Classe[] classe;

	/**
	 * 
	 * @param id 
	 * @param debut 
	 * @param fin 
	 * @param jour 
	 */
	public Creneau(String id, LocalTime debut, LocalTime fin, LocalDate jour) {
		this.id = id;
		this.debut = debut;
		this.fin = fin;
		this.jour = jour;
	}
};
