// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

/************************************************************/
/**
 * 
 */
public class Creneau {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private String debut;
	/**
	 * 
	 */
	private String fin;
	/**
	 * 
	 */
	private String jour;
	/**
	 * 
	 */
	public Classe[] classe;

	/**
	 * 
	 * @param id 
	 * @param debut 
	 * @param fin 
	 * @param jour 
	 */
	public Creneau(String id, String debut, String fin, String jour) {
	}
};
