// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;
enum Status {Eleve,Enseignant};
/************************************************************/
/**
 * 
 */
public class Personne {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private String prenom;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String mail;
	/**
	 * 
	 */
	private Status status;

	/**
	 * 
	 * @param id 
	 * @param prenom 
	 * @param nom 
	 * @param mail 
	 * @param status 
	 */
	public Personne(String id, String prenom, String nom, String mail, Status status) {
		
		this.id = id;
		this.prenom = prenom;
		this.nom = nom;
		this.mail = mail;
		this.status = status;
	}
};
