// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

/************************************************************/
/**
 * 
 */
public class Personne {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private String prenom;
	/**
	 * 
	 */
	private String nom;
	/**
	 * 
	 */
	private String mail;
	/**
	 * 
	 */
	private String status;

	/**
	 * 
	 * @param id 
	 * @param prenom 
	 * @param nom 
	 * @param mail 
	 * @param status 
	 */
	public Personne(String id, String prenom, String nom, String mail, String status) {
	}
};
