// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

/************************************************************/
/**
 * 
 */
public interface SessionInterface {
	/**
	 * 
	 */
	public void createEU();

	/**
	 * 
	 */
	public void createCreneau();

	/**
	 * 
	 */
	public void createClasse();

	/**
	 * 
	 */
	public void createSession();

	/**
	 * 
	 */
	public void changeCreneauSession();

	/**
	 * 
	 */
	public void createSessionCreneau();

	/**
	 * 
	 */
	public void deleteEU();

	/**
	 * 
	 */
	public void deleteCreneau();

	/**
	 * 
	 */
	public void deleteSession();

	/**
	 * 
	 */
	public void deleteClasse();
};
