// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Session;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class UniteEnseignement extends SqlUtils {
	/**
	 * 
	 */
	private String id;
	/**
	 * 
	 */
	private String code;
	/**
	 * 
	 */
	private String intitule;
	/**
	 * 
	 */
	private float cours;
	/**
	 * 
	 */
	private float td;
	/**
	 * 
	 */
	private float tp;
	/**
	 * 
	 */
	private float valeur;
	/**
	 * 
	 */
	public Classe[] classe;
	/**
	 * 
	 */
	public Creneau[] creneau;

	/**
	 * 
	 * @param id
	 * @param code
	 * @param intitule
	 * @param cours
	 * @param td
	 * @param tp
	 * @param valeur
	 */
	public UniteEnseignement(String id, String code, String intitule, float cours, float td, float tp, float valeur) {
		this.id = id;
		this.code = code;
		this.intitule = intitule;
		this.cours = cours;
		this.td = td;
		this.tp = tp;
		this.valeur = valeur;
	}

	public void save() {
		this.connect();
		this.requestUpdate(String.format("INSERT INTO UniteEnseignement VALUES('?','?','?',?,?,?,?)", this.id,
				this.code, this.intitule, String.valueOf(this.cours), String.valueOf(this.td), String.valueOf(this.tp),
				String.valueOf(this.valeur)));
		this.disconnect();
	}

	public void update() {
		this.connect();
		this.requestUpdate(String.format(
				"UPDATE UniteEnseignement SET code='?',intitule='?',cours=?,td=?,tp=?,valeur=? WHERE id='?'", this.code,
				this.intitule, String.valueOf(this.cours), String.valueOf(this.td), String.valueOf(this.tp),
				String.valueOf(this.valeur), this.id));
		this.disconnect();
	}

	public void delete() {
		this.connect();
		this.requestUpdate(String.format("DELETE FROM UniteEnseignement WHERE id='?'", this.id));
		this.disconnect();

	}

	public static UniteEnseignement getById(String id) {
		SqlUtils sql = new SqlUtils();
		sql.connect();
		ResultSet set = sql.requestSelect(String.format("SELECT * FROM UniteEnseignement WHERE id='?'", id));
		sql.disconnect();

		try {
			UniteEnseignement ue = new UniteEnseignement(set.getString("id"), set.getString("code"),
					set.getString("intitule"), set.getFloat("cours"), set.getFloat("td"), set.getFloat("tp"),
					set.getFloat("valeur"));
			return ue;
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}

	}

	public static List<UniteEnseignement> getAll() {
		SqlUtils sql = new SqlUtils();
		sql.connect();
		ResultSet set = sql.requestSelect(String.format("SELECT * FROM UniteEnseignement "));
		sql.disconnect();
		List<UniteEnseignement> result = new ArrayList<UniteEnseignement>();

		try {
			while (set.next()) {
				UniteEnseignement ue = new UniteEnseignement(set.getString("id"), set.getString("code"),
						set.getString("intitule"), set.getFloat("cours"), set.getFloat("td"), set.getFloat("tp"),
						set.getFloat("valeur"));
				result.add(ue);
			}
		} catch (SQLException e) {
			e.printStackTrace();
			return null;
		}
		return result;
	}
};
